source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'HTClassHomeMainFlowLayout_Example' do
  pod 'HTClassHomeMainFlowLayout', :path => '../'

  target 'HTClassHomeMainFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
